version: '3.8'
services:
  grpc-server:
    build:
      context: ./grpc-server
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    networks:
      - payslips-network

  grpc-client:
    build:
      context: ./grpc-client
      dockerfile: Dockerfile
    depends_on:
      - grpc-server
    networks:
      - payslips-network

  person:
    build:
      context: ./person
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - payslips-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

  employee:
    build:
      context: ./employee
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - person
    networks:
      - payslips-network
    environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
       SPRING_DATASOURCE_USERNAME: postgres
       SPRING_DATASOURCE_PASSWORD: admin

  organization:
    build:
      context: ./organization
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - person
    networks:
      - payslips-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

  database:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: payroll_db
    ports:
      - "5432:5432"
    networks:
      - payslips-network

networks:
  payslips-network:
    driver: bridge
