spring:
  cloud:
    gateway:
      routes:
        - id: person-service
          uri: http://localhost:8081
          predicates:
            - Path=/persons/**
          filters:
            - RewritePath=/persons/(?<segment>.*), /${segment}

        - id: employee-service
          uri: http://localhost:8082
          predicates:
            - Path=/employees/**
          filters:
            - RewritePath=/employees/(?<segment>.*), /${segment}

        - id: organization-service
          uri: http://localhost:8083
          predicates:
            - Path=/organizations/**
          filters:
            - RewritePath=/organizations/(?<segment>.*), /${segment}
