services:
  organization:
    build:
      context: .
      dockerfile: ./organization/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - person
    networks:
      - payslips-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
networks:
  payslips-network:
    external: true